In [19]:
#Cars data set , Objective is to predict the condition of the car. (Acceptable, unaccept, good, vgood...)

In [20]:
import pandas as pd
import numpy as np

In [21]:
cars_data=pd.read_csv("cars.csv",header=None)
cars_data.head()
cars_data.shape
cars_data.columns=['buying','maint','doors','persons','lug_boot','safety','classes'] ##assigning header to the dataset
cars_data.head()

buying  maint doors persons lug_boot safety classes
0  vhigh  vhigh     2       2    small    low   unacc
1  vhigh  vhigh     2       2    small    med   unacc
2  vhigh  vhigh     2       2    small   high   unacc
3  vhigh  vhigh     2       2      med    low   unacc
4  vhigh  vhigh     2       2      med    med   unacc

In [22]:
cars_data.head(50)

buying  maint doors persons lug_boot safety classes
0   vhigh  vhigh     2       2    small    low   unacc
1   vhigh  vhigh     2       2    small    med   unacc
2   vhigh  vhigh     2       2    small   high   unacc
3   vhigh  vhigh     2       2      med    low   unacc
4   vhigh  vhigh     2       2      med    med   unacc
5   vhigh  vhigh     2       2      med   high   unacc
6   vhigh  vhigh     2       2      big    low   unacc
7   vhigh  vhigh     2       2      big    med   unacc
8   vhigh  vhigh     2       2      big   high   unacc
9   vhigh  vhigh     2       4    small    low   unacc
10  vhigh  vhigh     2       4    small    med   unacc
11  vhigh  vhigh     2       4    small   high   unacc
12  vhigh  vhigh     2       4      med    low   unacc
13  vhigh  vhigh     2       4      med    med   unacc
14  vhigh  vhigh     2       4      med   high   unacc
15  vhigh  vhigh     2       4      big    low   unacc
16  vhigh  vhigh     2       4      big    med   unacc
17  vhigh  vhigh     2       4      big   high   unacc
18  vhigh  vhigh     2    more    small    low   unacc
19  vhigh  vhigh     2    more    small    med   unacc
20  vhigh  vhigh     2    more    small   high   unacc
21  vhigh  vhigh     2    more      med    low   unacc
22  vhigh  vhigh     2    more      med    med   unacc
23  vhigh  vhigh     2    more      med   high   unacc
24  vhigh  vhigh     2    more      big    low   unacc
25  vhigh  vhigh     2    more      big    med   unacc
26  vhigh  vhigh     2    more      big   high   unacc
27  vhigh  vhigh     3       2    small    low   unacc
28  vhigh  vhigh     3       2    small    med   unacc
29  vhigh  vhigh     3       2    small   high   unacc
30  vhigh  vhigh     3       2      med    low   unacc
31  vhigh  vhigh     3       2      med    med   unacc
32  vhigh  vhigh     3       2      med   high   unacc
33  vhigh  vhigh     3       2      big    low   unacc
34  vhigh  vhigh     3       2      big    med   unacc
35  vhigh  vhigh     3       2      big   high   unacc
36  vhigh  vhigh     3       4    small    low   unacc
37  vhigh  vhigh     3       4    small    med   unacc
38  vhigh  vhigh     3       4    small   high   unacc
39  vhigh  vhigh     3       4      med    low   unacc
40  vhigh  vhigh     3       4      med    med   unacc
41  vhigh  vhigh     3       4      med   high   unacc
42  vhigh  vhigh     3       4      big    low   unacc
43  vhigh  vhigh     3       4      big    med   unacc
44  vhigh  vhigh     3       4      big   high   unacc
45  vhigh  vhigh     3    more    small    low   unacc
46  vhigh  vhigh     3    more    small    med   unacc
47  vhigh  vhigh     3    more    small   high   unacc
48  vhigh  vhigh     3    more      med    low   unacc
49  vhigh  vhigh     3    more      med    med   unacc

In [23]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
buying      1728 non-null object
maint       1728 non-null object
doors       1728 non-null object
persons     1728 non-null object
lug_boot    1728 non-null object
safety      1728 non-null object
classes     1728 non-null object
dtypes: object(7)
memory usage: 94.6+ KB


In [24]:
cars_data.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64

In [25]:
cars_df=pd.DataFrame.copy(cars_data)
colname=cars_df.columns[:] #all variables are catagorical so we will apply Label encoding to all X variables.
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [26]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

for x in colname:
    cars_df[x]=le.fit_transform(cars_df[x]) #fit and transform are two steps of label encoding

cars_df.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       3      3      0        0         2       1        2
1       3      3      0        0         2       2        2
2       3      3      0        0         2       0        2
3       3      3      0        0         1       1        2
4       3      3      0        0         1       2        2

In [3]:
cars_data.classes.value_counts() #level counts
#acc=0
#good=1
#unacc=2
#vgood=3

X=cars_df.values[:,:-1] #all rows and all columns except last one
Y=cars_df.values[:,-1] #all rows and last column


NameError: name 'cars_data' is not defined

In [2]:
#Standard scaler reduces the data variations (sort of outlier treatment) 
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)

NameError: name 'X' is not defined

In [30]:
from sklearn.model_selection import train_test_split
#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.3, random_state=10)


In [1]:
##Running Decision Tree Model

#Predicting using the Decision_Tree_Classifier
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree=DecisionTreeClassifier(random_state=10,min_samples_leaf=3,max_depth=10)

#fit the model on the train data and predict the values
model_DecisionTree.fit(X_train,Y_train)


NameError: name 'X_train' is not defined

In [32]:
Y_pred=model_DecisionTree.predict(X_test) #predicting Y values
#print(Y_pred)
#print(list(zip(Y_test,Y_pred)))

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 98   2   2   0]
 [  2  15   2   2]
 [  7   0 364   0]
 [  3   0   0  22]]
0.9614643545279383
              precision    recall  f1-score   support

           0       0.89      0.96      0.92       102
           1       0.88      0.71      0.79        21
           2       0.99      0.98      0.99       371
           3       0.92      0.88      0.90        25

   micro avg       0.96      0.96      0.96       519
   macro avg       0.92      0.88      0.90       519
weighted avg       0.96      0.96      0.96       519



In [4]:
#After training the model##Variable importance check, higher values are better   
print(list(zip(colname,model_DecisionTree.feature_importances_)))

#generate the file (saved as text in directory) and upload the code(in text file) in webgraphviz.com to plot the decision tree
from sklearn import tree
with open("model_DecisionTree.txt", "w") as f: #.txt file will be created and stored in python library (C:\Users\Manoj Nahak)
    f = tree.export_graphviz(model_DecisionTree, feature_names=colname[:-1],out_file=f)


NameError: name 'colname' is not defined

# SVM

In [41]:
##using SVM
from sklearn import svm
svc_model=svm.SVC(kernel='rbf',C=40,gamma=0.1)
#from sklearn.linear_model import LogsiticRegression
#svc_model=LogisticRegression()
svc_model.fit(X_train,Y_train)
Y_pred=svc_model.predict(X_test)
print(list(Y_pred))


[2, 2, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3, 2, 0, 2, 2, 2, 2, 2, 0, 1, 3, 1, 2, 0, 2, 0, 2, 2, 2, 2, 3, 2, 2, 0, 0, 2, 2, 3, 2, 2, 2, 1, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 3, 2, 2, 0, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 1, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 3, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 0, 2, 1, 0, 2, 2, 2, 2, 0, 3, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 0, 2, 2, 2, 3, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 0, 2, 0, 3, 3, 0, 2, 0, 2, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 0, 2, 2, 2, 0, 2, 

In [42]:
Y_pred_col=list(Y_pred)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 98   2   2   0]
 [  0  21   0   0]
 [  0   0 371   0]
 [  0   0   0  25]]
0.9922928709055877
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       102
           1       0.91      1.00      0.95        21
           2       0.99      1.00      1.00       371
           3       1.00      1.00      1.00        25

   micro avg       0.99      0.99      0.99       519
   macro avg       0.98      0.99      0.98       519
weighted avg       0.99      0.99      0.99       519



In [43]:
##using logistic regression

from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression()
#fitting training data to the model
classifier.fit(X_train,Y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [44]:
Y_pred=classifier.predict(X_test)
#print(list(zip(Y_test,Y_pred)))



In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))



[[ 22   0  80   0]
 [  3   0  18   0]
 [ 30   0 341   0]
 [ 11   0  14   0]]
0.6994219653179191
              precision    recall  f1-score   support

           0       0.33      0.22      0.26       102
           1       0.00      0.00      0.00        21
           2       0.75      0.92      0.83       371
           3       0.00      0.00      0.00        25

   micro avg       0.70      0.70      0.70       519
   macro avg       0.27      0.28      0.27       519
weighted avg       0.60      0.70      0.64       519



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Ensemble Model Techniques

In [46]:
#predicting using the Bagging_Classifier
from sklearn.ensemble import ExtraTreesClassifier

model=(ExtraTreesClassifier(50,random_state=10))
#fit the model on the data and predict the values
model=model.fit(X_train,Y_train)

Y_pred=model.predict(X_test)


In [47]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))


[[100   0   2   0]
 [  3  18   0   0]
 [  3   0 368   0]
 [  1   2   0  22]]
0.9788053949903661
              precision    recall  f1-score   support

           0       0.93      0.98      0.96       102
           1       0.90      0.86      0.88        21
           2       0.99      0.99      0.99       371
           3       1.00      0.88      0.94        25

   micro avg       0.98      0.98      0.98       519
   macro avg       0.96      0.93      0.94       519
weighted avg       0.98      0.98      0.98       519



In [48]:
##Randomforest
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=(RandomForestClassifier(100,random_state=10))
#fit the model on the data and predict the values
model_RandomForest.fit(X_train,Y_train)



RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=10, verbose=0, warm_start=False)

In [49]:
Y_pred=model_RandomForest.predict(X_test)

from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[ 99   3   0   0]
 [  1  19   0   1]
 [  2   0 369   0]
 [  2   0   0  23]]
0.9826589595375722
              precision    recall  f1-score   support

           0       0.95      0.97      0.96       102
           1       0.86      0.90      0.88        21
           2       1.00      0.99      1.00       371
           3       0.96      0.92      0.94        25

   micro avg       0.98      0.98      0.98       519
   macro avg       0.94      0.95      0.95       519
weighted avg       0.98      0.98      0.98       519

