In [ ]:
#predict the income of a person by using Logistic Regression

In [4]:
import pandas as pd
import numpy as np

In [5]:
adult_df = pd.read_csv (r'E:\Imarticus DSP 24\Python\Logistic Regression\adult_data.csv', 
                        header=None, delimiter=" *, *", engine='python')
adult_df.head()

0                 1       2          3   4                   5   \
0  39         State-gov   77516  Bachelors  13       Never-married   
1  50  Self-emp-not-inc   83311  Bachelors  13  Married-civ-spouse   
2  38           Private  215646    HS-grad   9            Divorced   
3  53           Private  234721       11th   7  Married-civ-spouse   
4  28           Private  338409  Bachelors  13  Married-civ-spouse   

                  6              7      8       9     10  11  12  \
0       Adm-clerical  Not-in-family  White    Male  2174   0  40   
1    Exec-managerial        Husband  White    Male     0   0  13   
2  Handlers-cleaners  Not-in-family  White    Male     0   0  40   
3  Handlers-cleaners        Husband  Black    Male     0   0  40   
4     Prof-specialty           Wife  Black  Female     0   0  40   

              13     14  
0  United-States  <=50K  
1  United-States  <=50K  
2  United-States  <=50K  
3  United-States  <=50K  
4           Cuba  <=50K

In [6]:
adult_df.shape

(32561, 15)

In [7]:
adult_df.columns=['age','workclass','fnlwgt', 'education', 'education_num','marital_status', 'occupation', 'relationship',
'race', 'sex', 'capital_gain', 'capital_loss','hours_per_week', 'native_country', 'income']
adult_df.head()

age         workclass  fnlwgt  education  education_num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital_status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital_gain  capital_loss  hours_per_week native_country income  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

In [8]:
adult_df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [9]:
adult_df=adult_df.replace(['?'],np.nan)

In [10]:
adult_df.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [11]:
adult_df2=pd.DataFrame.copy(adult_df)

In [12]:
adult_df2=adult_df2.drop(['education','fnlwgt'],axis=1)

In [13]:
adult_df2.head()

age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race     sex  capital_gain  \
0       Adm-clerical  Not-in-family  White    Male          2174   
1    Exec-managerial        Husband  White    Male             0   
2  Handlers-cleaners  Not-in-family  White    Male             0   
3  Handlers-cleaners        Husband  Black    Male             0   
4     Prof-specialty           Wife  Black  Female             0   

   capital_loss  hours_per_week native_country income  
0             0              40  United-States  <=50K  
1             0              13  United-States  <=50K  
2             0              40  United-States  <=50K  
3             0              40  United-States  <=50K  
4             0              40           Cuba  <=50K

In [14]:
for value in ['workclass','occupation','native_country']:adult_df2[value].fillna(adult_df2[value].mode()[0],inplace=True)

In [15]:
adult_df2.isnull().sum()

age               0
workclass         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [16]:
#generic code to save the catagorical variable into a list
colname=[]
for x in adult_df2.columns[:]:
    if adult_df2[x].dtype=='object':
        colname.append(x)
colname

['workclass',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native_country',
 'income']

In [17]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
for x in colname:
    adult_df2[x]=le.fit_transform(adult_df2[x])

In [18]:
adult_df2.head()

age  workclass  education_num  marital_status  occupation  relationship  \
0   39          6             13               4           0             1   
1   50          5             13               2           3             0   
2   38          3              9               0           5             1   
3   53          3              7               2           5             0   
4   28          3             13               2           9             5   

   race  sex  capital_gain  capital_loss  hours_per_week  native_country  \
0     4    1          2174             0              40              38   
1     4    1             0             0              13              38   
2     4    1             0             0              40              38   
3     2    1             0             0              40              38   
4     2    0             0             0              40               4   

   income  
0       0  
1       0  
2       0  
3       0  
4       0

In [19]:
adult_df2.dtypes

age               int64
workclass         int32
education_num     int64
marital_status    int32
occupation        int32
relationship      int32
race              int32
sex               int32
capital_gain      int64
capital_loss      int64
hours_per_week    int64
native_country    int32
income            int32
dtype: object

In [20]:
X=adult_df2.values[:,:-1]
Y=adult_df2.values[:,-1]

In [21]:
type(Y)

numpy.ndarray

In [22]:
Y=Y.astype(int)

In [23]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=100)
print(X)
print(Y)

[[39  6 13 ...  0 40 38]
 [50  5 13 ...  0 13 38]
 [38  3  9 ...  0 40 38]
 ...
 [58  3  9 ...  0 40 38]
 [22  3  9 ...  0 20 38]
 [52  4  9 ...  0 40 38]]
[0 0 0 ... 0 0 1]


In [24]:
#model building
from sklearn.linear_model import LogisticRegression

classifier=LogisticRegression()
classifier.fit(X_train,Y_train)
Y_pred=classifier.predict(X_test)

print(classifier.coef_)
print(classifier.intercept_)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[[ 2.93197391e-02 -1.14126417e-01  3.05899867e-01 -2.11294363e-01
  -1.18954307e-02 -1.84654167e-01  4.72955175e-02  7.84752353e-01
   3.07916788e-04  6.40588104e-04  2.73159074e-02 -8.01167417e-03]]
[-6.3138512]


In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print(classification_report(Y_test,Y_pred))

print(accuracy_score(Y_test,Y_pred))


[[7030  398]
 [1282 1059]]
              precision    recall  f1-score   support

           0       0.85      0.95      0.89      7428
           1       0.73      0.45      0.56      2341

   micro avg       0.83      0.83      0.83      9769
   macro avg       0.79      0.70      0.73      9769
weighted avg       0.82      0.83      0.81      9769

0.8280274337189067


In [26]:
y_pred_prob = classifier.predict_proba(X_test)
print(y_pred_prob)

[[0.89500631 0.10499369]
 [0.87416991 0.12583009]
 [0.86137366 0.13862634]
 ...
 [0.59608526 0.40391474]
 [0.79806451 0.20193549]
 [0.54511838 0.45488162]]
