In [1]:
import numpy as np
np.__version__   #attribute used to get the version of numpy

'1.16.2'

In [2]:
a=np.array([1,2,3])
print(a)
print(type(a))
print(a.ndim) #returns dimension of array

[1 2 3]
<class 'numpy.ndarray'>
1


In [6]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)]) #list of tuples
print(a)
print(a.ndim)
print(a.shape) #gives no of rows and columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [8]:
a=np.array([(1,2,3,4),(4,5,6)]) #unequal element
print(a)
print(a.ndim)

[(1, 2, 3, 4) (4, 5, 6)]
1


In [6]:
#ones function
a,b=np.ones((2,3,4)) #2= no of arrays, 3 = no fo rows, 4= no of columns
print(a)
print()
#print(b)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



In [17]:
a,b=np.zeros((2,3,4), dtype = np.int)
print(a)
print()
print(b)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
c,d=np.full((2,4,3),9)
print(c)
print()
print(d)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]


In [15]:
a=np.identity(3,dtype=np.int) #diagnol values will be 1
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [7]:
a=np.random.random((5,2)) #np = parent package, random = sub package, random (function)
#print(a)
#a=np.random.random_integers(50,100,(3,4))
a=np.random.randint(50,70,(3,4))
print(a)

[[58 51 58 58]
 [62 65 69 65]
 [58 59 60 68]]


In [ ]:
#array matrix
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:")) 

#matrix=[]
# Initialize matrix 
print("Enter the entries rowwise:") 
  
# For user input 
for i in range(R):          # A for loop for row entries 
    a =[]
    for j in range(C):      # A for loop for column entries 
         a.append(int(input())) 
    matrix.append(a) 
  
# For printing the matrix 
for i in range(R): 
    for j in range(C): 
        print(matrix[i][j], end = " ") 
    print()

In [13]:
a=np.array([(1,2,3,4),(4,5,6,7)])
print(a)
print(a.size) # will give the total no of elements in array
print(a.shape)

[[1 2 3 4]
 [4 5 6 7]]
8
(2, 4)


In [17]:
#a=np.resize(a,(6,3)) #can shrink or enlarge the size of array
a=np.reshape(a,(3,6)) #reshape will hold the exact elemnts of array and change the shape
print(a)

[[1 2 3 4 4 5]
 [6 7 1 2 3 4]
 [4 5 6 7 1 2]]


In [53]:
#indexing and slicing
a=np.array([(1,2,3,4),(3,4,5,6),(8,9,10,11)])
print(a)

print(a[0,2]) #will give first row third element
print(a[:,2]) #will give all rows and third column
print()
print(a[0:2,:]) #will give the first two rows and all columns
#creating a new array (subset of array)
print()
b=(a[0:2,:])
print(b)

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 8  9 10 11]]
3
[ 3  5 10]

[[1 2 3 4]
 [3 4 5 6]]

[[1 2 3 4]
 [3 4 5 6]]


In [23]:
#a=np.linspace(1,10,4)
#print(a)

a=np.arange(0,25,5)
print(a)
print()
#even no from 100 to 70
a=np.arange(100,69,-2)
print(a)

[ 0  5 10 15 20]

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70]


In [69]:
#aggregate functions
a=np.array([(8,9),(10,11),(12,13)])
print(len(a)) #will give the count of tuples from array
print(a.size) #will give th count of all elements from array
print(a.min())
print(a.max())
print(a.sum())
print(a.sum()/a.size)
print(a.mean())


3
6
8
13
63
10.5
10.5


In [24]:
#math function
a=np.array([(1,0,4),(9,16,25)])

print(np.sqrt(a))
print(np.std(a)) #standard deviation
print(np.log(a))
b=np.sqrt(a) #antilog
print(b.round(2))

[[1. 0. 2.]
 [3. 4. 5.]]
8.89600409672168
[[0.               -inf 1.38629436]
 [2.19722458 2.77258872 3.21887582]]
[[1. 0. 2.]
 [3. 4. 5.]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log
  


In [73]:
x= np.array([(1,2),(3,4)])
y= np.array([(5,6),(3,4)])
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
#print(np.remainder())

print(x@y) #for dot matrix
#print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [3 4]]
[[6 8]
 [6 8]]
[[-4 -4]
 [ 0  0]]
[[ 5 12]
 [ 9 16]]
[[0.2        0.33333333]
 [1.         1.        ]]
[[1 2]
 [0 0]]
[[11 14]
 [27 34]]


In [25]:
#help
#?np.mean
print(np.lookfor("mean"))
#help(np.zeros)

TypeError: 'NoneType' object is not iterable

In [83]:
#joining arrays
d=np.concatenate((x,y),axis=0) #axis = 0 rowwise concatenate and 1 for columwise concatenate
e=np.concatenate((x,y),axis=1)
print(d)
print(e)
print()

#or

print(np.vstack((x,y))) #rowwise concatenate
print(np.hstack((x,y))) #column wise concatenate

[[1 2]
 [3 4]
 [5 6]
 [3 4]]
[[1 2 5 6]
 [3 4 3 4]]

[[1 2]
 [3 4]
 [5 6]
 [3 4]]
[[1 2 5 6]
 [3 4 3 4]]


In [84]:
#converting array into single row
print(x)
z=x.ravel() #converting 2 dim arry to 1 dim array, it will be flattening the array
print(z)
print(z.reshape(2,2)) #converting 1 dim array to 2 dim array

[[1 2]
 [3 4]]
[1 2 3 4]
[[1 2]
 [3 4]]


In [33]:
#joining the array when there is diff dimension array use 'append'
x = np.array([(1,2,3),(4,5,6)])
y = np.array([(6,7),(9,10)])
new_array = np.append(x,y)
print(x,'\n')
print(y,'\n')
print(new_array,'\n')
new_array = np.reshape(new_array,(2,5))
print(new_array)

[[1 2 3]
 [4 5 6]] 

[[ 6  7]
 [ 9 10]] 

[ 1  2  3  4  5  6  6  7  9 10] 

[[ 1  2  3  4  5]
 [ 6  6  7  9 10]]


In [35]:
#adding elements inbetween the arrays
x=np.array([(1,2,3),(3,4,5)])
new_array=np.insert(x,[1,3],[500,700]) #insert(varaible,[index no],[value need to be insert])
print(new_array)
print(x)

[  1 500   2   3 700   3   4   5]
[[1 2 3]
 [3 4 5]]


In [91]:
#deleting elements from array
new_array = np.delete(new_array,[1,2]) #deleting values from index no 1 and 2
print(new_array)

[ 1  3 10  3  4  5]


In [93]:
#updating an array
x=np.array([(1,2,3),(4,5,6)])
print(x)
print()
x[0,1]=7
print(x)

[[1 2 3]
 [4 5 6]]

[[1 7 3]
 [4 5 6]]


In [37]:
my_array2 = np.genfromtxt(r'C:\Users\Manoj Nahak\Desktop\array_data.txt',
                          skip_header=1, delimiter=',',filling_values=0,unpack=True,dtype=np.int)
#r is used to specify the path as string
#skip header to exclude reading the column names
#filling values to treat the missing values
#unpack = True will transpose the order of elements in columnwise
print(my_array2)

[[  1   4   7]
 [  2 500   8]
 [  3   6   9]]


In [38]:
#updating an array element from value 500 to 5
my_array2[1,1]=5
my_array2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])