In [1]:
#Objective is to predict salary from adult_data which falls under salary bucket (0 and 1) with range as <=50K and >50K.

In [2]:
import pandas as pd
import numpy as np

In [5]:
adult_df = pd.read_csv(r'E:\Imarticus DSP 24\Python\Logistic Regression\adult_data.csv', header= None,
                       delimiter=' *, *')
adult_df.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


0                 1       2          3   4                   5   \
0  39         State-gov   77516  Bachelors  13       Never-married   
1  50  Self-emp-not-inc   83311  Bachelors  13  Married-civ-spouse   
2  38           Private  215646    HS-grad   9            Divorced   
3  53           Private  234721       11th   7  Married-civ-spouse   
4  28           Private  338409  Bachelors  13  Married-civ-spouse   

                  6              7      8       9     10  11  12  \
0       Adm-clerical  Not-in-family  White    Male  2174   0  40   
1    Exec-managerial        Husband  White    Male     0   0  13   
2  Handlers-cleaners  Not-in-family  White    Male     0   0  40   
3  Handlers-cleaners        Husband  Black    Male     0   0  40   
4     Prof-specialty           Wife  Black  Female     0   0  40   

              13     14  
0  United-States  <=50K  
1  United-States  <=50K  
2  United-States  <=50K  
3  United-States  <=50K  
4           Cuba  <=50K

In [4]:
adult_df.shape #to get no of rows and columns

(32561, 15)

In [7]:
#assigning columns headers
adult_df.columns = ['age','workclass', 'fnlwgt', 'education', 'education_num',
'marital_status', 'occupation', 'relationship',
'race', 'sex', 'capital_gain', 'capital_loss',
'hours_per_week', 'native_country', 'income']
adult_df.head()

age         workclass  fnlwgt  education  education_num  \
0   39         State-gov   77516  Bachelors             13   
1   50  Self-emp-not-inc   83311  Bachelors             13   
2   38           Private  215646    HS-grad              9   
3   53           Private  234721       11th              7   
4   28           Private  338409  Bachelors             13   

       marital_status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capital_gain  capital_loss  hours_per_week native_country income  
0          2174             0              40  United-States  <=50K  
1             0             0              13  United-States  <=50K  
2             0             0              40  United-States  <=50K  
3             0             0              40  United-States  <=50K  
4             0             0              40           Cuba  <=50K

# pre-processing the DATA

In [9]:
adult_df.isnull().sum() #null value are in special characters i.e ' ?'

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [16]:
adult_df.eq(r'?').any(1).sum() #to get count of no of rows with special character

2399

In [17]:
adult_df.eq(r'?').sum() #to get count of special character in each variable

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [18]:
adult_df = adult_df.replace(['?'], np.nan) #here we have replaced the '?' with nan

In [20]:
adult_df.isnull().sum() #getting count of null values

age                  0
workclass         1836
fnlwgt               0
education            0
education_num        0
marital_status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital_gain         0
capital_loss         0
hours_per_week       0
native_country     583
income               0
dtype: int64

In [21]:
df1 = adult_df.copy() #creating copy of DataFrame

In [23]:
df1 = df1.drop(['education','fnlwgt'], axis = 1)

In [25]:
df1.head(2)

age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race   sex  capital_gain  capital_loss  hours_per_week  \
0  Not-in-family  White  Male          2174             0              40   
1        Husband  White  Male             0             0              13   

  native_country income  
0  United-States  <=50K  
1  United-States  <=50K

In [26]:
#code to view the mode values of each variables and that will be replaced with the missing values
df1.workclass.mode()

0    Private
dtype: object

In [28]:
df1.occupation.mode()

0    Prof-specialty
dtype: object

In [29]:
df1.native_country.mode()

0    United-States
dtype: object

In [30]:
#replace the missing values with the mode vlaues of each columns, everytime the mode value will be at 0th index
for value in ['workclass','occupation','native_country']:
    df1[value].fillna(df1[value].mode()[0], inplace= True)

In [32]:
df1.isnull().sum()

age               0
workclass         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [38]:
#gives the unique level value counts for columns
df1.income.value_counts()

<=50K    24720
>50K      7841
Name: income, dtype: int64

In [41]:
#generic code for getting catagoricals variable and storing them in a list
cat_var=[]
for x in df1.columns[:]:
    if df1[x].dtype=='object':
        cat_var.append(x)
cat_var

['workclass',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native_country',
 'income']

In [42]:
#label encoder only for catagorical variable
from sklearn import preprocessing

le=preprocessing.LabelEncoder()

for x in cat_var:
    df1[x]=le.fit_transform(df1[x])

In [43]:
df1.head(3)

age  workclass  education_num  marital_status  occupation  relationship  \
0   39          6             13               4           0             1   
1   50          5             13               2           3             0   
2   38          3              9               0           5             1   

   race  sex  capital_gain  capital_loss  hours_per_week  native_country  \
0     4    1          2174             0              40              38   
1     4    1             0             0              13              38   
2     4    1             0             0              40              38   

   income  
0       0  
1       0  
2       0

In [53]:
df1.dtypes

age               int64
workclass         int32
education_num     int64
marital_status    int32
occupation        int32
relationship      int32
race              int32
sex               int32
capital_gain      int64
capital_loss      int64
hours_per_week    int64
native_country    int32
income            int32
dtype: object

In [47]:
#storing the varaibles in X and Y
X = df1.values[:,:-1] #store all the rows and all coumns excluding the last column
Y = df1.values[:,-1] #store all rows and the last column

In [48]:
type(X)

numpy.ndarray

In [49]:
type(Y)

numpy.ndarray

SCALING

In [52]:
#implementing standardziation here standardscaler is a function
from sklearn import preprocessing

scale = preprocessing.StandardScaler()

scale.fit(X)
X=scale.transform(X)
print(X)

[[ 0.03067056  2.62429763  1.13473876 ... -0.21665953 -0.03542945
   0.26136999]
 [ 0.83710898  1.72109965  1.13473876 ... -0.21665953 -2.22215312
   0.26136999]
 [-0.04264203 -0.08529633 -0.42005962 ... -0.21665953 -0.03542945
   0.26136999]
 ...
 [ 1.42360965 -0.08529633 -0.42005962 ... -0.21665953 -0.03542945
   0.26136999]
 [-1.21564337 -0.08529633 -0.42005962 ... -0.21665953 -1.65522476
   0.26136999]
 [ 0.98373415  0.81790166 -0.42005962 ... -0.21665953 -0.03542945
   0.26136999]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


# Data Partition
""" 1) Based on condition - used usually in case of time series 2) based on no of observation 3) Random Sampling --> train_test_split """

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3, random_state=10)

# MODEL BUILDING

In [57]:
from sklearn.linear_model import LogisticRegression

#create a model object
m1 = LogisticRegression()

#fitting the training data into model, (i.e training the model on 70% train data)
m1.fit(X_train, Y_train)

#using the model
Y_pred = m1.predict(X_test) #applying the model on 30% test data and storing the predicted values in Y_pred

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [58]:
print(m1.coef_) #to get slope values (B1,B2,B3...)

[[ 0.47898827 -0.10448293  0.86285082 -0.3481469  -0.0165719  -0.18074806
   0.11569239  0.42805994  2.4277355   0.28594931  0.37942052  0.00878949]]


In [60]:
 print(m1.intercept_) #to get the B0 value

[-1.50131013]


In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [63]:
print(confusion_matrix(Y_test, Y_pred))

#confusion matrix:-
                    #predict -ve       predict +ve
# -ve case(0)        true negative    false positive
# +ve caase(1)       false negative   ture positive

#Accuracy_score=  TN+TP/TN+TP+FP+FN

[[7017  406]
 [1316 1030]]


In [65]:
print(accuracy_score(Y_test, Y_pred))

0.8237281195618794


In [66]:
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89      7423
           1       0.72      0.44      0.54      2346

   micro avg       0.82      0.82      0.82      9769
   macro avg       0.78      0.69      0.72      9769
weighted avg       0.81      0.82      0.81      9769



# Tuning the Model by Adjusting the Threshold

In [67]:
#proba is used to calculate prediction on basis of threshold which we decide
#without proba it only predict or calculate on basis of default threshold(.5)
Y_pred_prob = m1.predict_proba(X_test)
print(Y_pred_prob)

[[0.96860653 0.03139347]
 [0.97030158 0.02969842]
 [0.23862252 0.76137748]
 ...
 [0.81402337 0.18597663]
 [0.82524908 0.17475092]
 [0.1567879  0.8432121 ]]


In [73]:
#changing the Default Threashold from 0.5 to 0.45
Y_pred_class = []
for value in Y_pred_prob[:,1]:
    if value > 0.45:
        Y_pred_class.append(1)
    else:
        Y_pred_class.append(0)


In [74]:
print(Y_pred_class)

[0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 

In [75]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [77]:
print(confusion_matrix(Y_test,Y_pred_class))

[[6878  545]
 [1189 1157]]


In [78]:
print(accuracy_score(Y_test,Y_pred_class))

0.8224997440884431


In [79]:
print(classification_report(Y_test,Y_pred_class))

              precision    recall  f1-score   support

           0       0.85      0.93      0.89      7423
           1       0.68      0.49      0.57      2346

   micro avg       0.82      0.82      0.82      9769
   macro avg       0.77      0.71      0.73      9769
weighted avg       0.81      0.82      0.81      9769



In [81]:
#generic code to get the threashold value

for a in np.arange(0,1,0.05): #range from 0 to 1 with difference of .05
    pred_me = np.where(Y_pred_prob[:,1] > a, 1, 0)
    cfm = confusion_matrix(Y_test, pred_me)
    error = cfm[0,1]+cfm[1,0] #type 1 error + type 2 error
    print(a,":",error,": Type 2 error :", cfm[1,0], ", type 1 error :", cfm[0,1])

0.0 : 7423 : Type 2 error : 0 , type 1 error : 7423
0.05 : 5137 : Type 2 error : 66 , type 1 error : 5071
0.1 : 3865 : Type 2 error : 158 , type 1 error : 3707
0.15000000000000002 : 3089 : Type 2 error : 272 , type 1 error : 2817
0.2 : 2526 : Type 2 error : 438 , type 1 error : 2088
0.25 : 2172 : Type 2 error : 610 , type 1 error : 1562
0.30000000000000004 : 1956 : Type 2 error : 765 , type 1 error : 1191
0.35000000000000003 : 1846 : Type 2 error : 938 , type 1 error : 908
0.4 : 1768 : Type 2 error : 1072 , type 1 error : 696
0.45 : 1734 : Type 2 error : 1189 , type 1 error : 545
0.5 : 1722 : Type 2 error : 1316 , type 1 error : 406
0.55 : 1731 : Type 2 error : 1417 , type 1 error : 314
0.6000000000000001 : 1746 : Type 2 error : 1527 , type 1 error : 219
0.65 : 1781 : Type 2 error : 1623 , type 1 error : 158
0.7000000000000001 : 1810 : Type 2 error : 1706 , type 1 error : 104
0.75 : 1853 : Type 2 error : 1782 , type 1 error : 71
0.8 : 1917 : Type 2 error : 1870 , type 1 error : 47
0.85

# ROC and AUC